-- ============================================================
-- user_settings 表：为每个租户（auth.users）存储私有凭证
-- ============================================================

-- 1. 建表
CREATE TABLE IF NOT EXISTS user_settings (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- 闲鱼 / 闲管家 API 凭证（用于同步订单）
  goofish_app_key    TEXT,
  goofish_app_secret TEXT,

  -- 顺丰速运电子面单凭证
  sf_partner_id      TEXT,
  sf_check_word      TEXT,
  sf_sender_name     TEXT,
  sf_sender_phone    TEXT,
  sf_sender_address  TEXT
);

-- 2. 每个用户最多只能有一条配置记录
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_settings_user_id ON user_settings(user_id);

-- 3. 闲鱼 AppKey 唯一索引（方便 webhook 按 appId 查找用户）
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_settings_goofish_app_key
  ON user_settings(goofish_app_key)
  WHERE goofish_app_key IS NOT NULL;

-- 4. 自动更新时间戳
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER user_settings_updated_at
  BEFORE UPDATE ON user_settings
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- Row Level Security (RLS)
-- ============================================================
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;

-- 策略：仅用户本人可读取自己的配置
CREATE POLICY "Users can view own settings"
  ON user_settings FOR SELECT
  USING (auth.uid() = user_id);

-- 策略：仅用户本人可插入自己的配置（不存在时才可插入）
CREATE POLICY "Users can insert own settings"
  ON user_settings FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- 策略：仅用户本人可更新自己的配置
CREATE POLICY "Users can update own settings"
  ON user_settings FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- 策略：仅用户本人可删除自己的配置
CREATE POLICY "Users can delete own settings"
  ON user_settings FOR DELETE
  USING (auth.uid() = user_id);

-- ============================================================
-- orders 表：为每个订单关联所属租户
-- ============================================================

-- 5. 为 orders 表增加 user_id 列
ALTER TABLE IF EXISTS public.orders
  ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;

-- 6. 为 user_id 建索引（加速按租户查询）
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders(user_id);

-- 7. 允许 orders 表使用 RLS（如果尚未启用）
ALTER TABLE IF EXISTS public.orders ENABLE ROW LEVEL SECURITY;

-- 8. orders RLS 策略：用户只能读写自己创建的订单
CREATE POLICY "Users can view own orders"
  ON public.orders FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own orders"
  ON public.orders FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own orders"
  ON public.orders FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own orders"
  ON public.orders FOR DELETE
  USING (auth.uid() = user_id);
